amara_user_id: 'captions2'
amara_key: "c639e50c5ac807d3dd828396ce23b08c1143bf80"
youtube_key: 'AIzaSyAUi7ZjMMeBmwY9NTdTJ4JkBgfobzNZIaM'
vimeo_client_identifier: "923611fe4bc05060cbe0496f5a4ce50b6b27c8f9"
vimeo_client_secret: "ffB+H74wxDWECvm41WhQmYcc8O+rmlIhR4dQMCaeGKXiD7yjMO9vgyC6E6nY0kqJXGEZ0WTIUpF2STQaon/cuBiGlGgQLbJErUyyyPwi9qG52Ug7ZWjQPMt1mBPgvHHP"
