---
kind: Deployment
apiVersion: v1
metadata:
  name: bluegreenlb
  labels:
    app: bluegreenlb
spec:
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: blue
  type: LoadBalancer
  externalIPs:
    - 192.168.1.1
