---

- name: "Deploy EKS Cluster"
  hosts: web
  user: jenkins
  gather_facts: true

  tasks:

    - name: "Create Cluster"
      shell: |
        eksctl create cluster --name capstone-cluster --version <1.18>

