---

- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: true

  tasks:

    - name: "Login to Docker Hub"
      shell: sudo docker login --username fontaineconsult --password !Babybops!


    - name: "Pull Docker Image"
      shell: sudo docker pull fontaineconsult/capstone:fortesting


    - name: "Run Docker Image"
      shell: sudo docker run -i -p 80:80 fontaineconsult/capstone apachectl -D FOREGROUND
